### ISSUE TITLE
Markdown as basic format for cards

### ISSUE THREAD

**Issue by vvscode** [memory-cards/rfcs#1]
I propose to use markdown as the default cards format. For me - common fields for any cards should be - `title`, `description`, `topics`, `tags` and after that custom `body` depends on card format.

`Title` / `description` just for info. They might not be used on rendering card, but they might be useful for comments.

So it might be like next ( https://github.com/remarkjs/remark-frontmatter ):
```markdown
---
title: Some card title

description: Some card description

topics: nodejs, react

tags: junior, minsk
___

Body of card below
```
and custom `body` below ( depends on card type )

**Comment by zenby** [comment]
Vasiliy, I completely agree with you.

**Comment by vvscode** [comment]
@zenby  from another point of view - if we're going use `yaml` as a tool for cards description  - we could use similar in simple language and have yaml-schema validations. That might save a lot of time on debugging for cases when we don't realize why some card hasn't been compiled

**Comment by vvscode** [comment]
Comparation for `json`/`yaml` / `js`:

```json
{
  "type": "choose_options",
  "card": {
    "question": "What is javascript framework?",
    "answers": [
      {
        "text": "Angular",
        "correct": true
      },
      {
        "text": "Zend",
        "correct": false
      },
      {
        "text": "Пингвин",
        "correct": false
      }
    ],
    "tags": [
      "js",
      "frontend"
    ]
  }
}
```
---
```yaml
type: choose_options
card:
  question: What is javascript framework?
  answers:
  - text: Angular
    correct: true
  - text: Zend
    correct: false
  - text: Пингвин
    correct: false
  tags:
  - js
  - frontend
```

---
```javascript
module.exports = {
  type: "choose_options",
  card: {
    question: "What is javascript framework?",
    answers: [
      {
        text: "Angular",
        correct: true
      },
      {
        text: "Zend",
        correct: false
      },
      {
        text: "Пингвин",
        correct: false
      }
    ],
    tags: ["js", "frontend"]
  }
};
```
